img_size: 224
num_workers: 4
precision: fp32
n_tasks: 0

# for sampling 10 images
shot: 4

# encoder
enc: swin

# training arguments
image_augmentation: False
binary_augmentation: False
batch_size: 1
val_batch_size: 1
n_steps: 300000
optimizer: adamw
lr: 0.0001
scheduler: Fasle
lr_warmup: 1000
lr_warmup_scale: 0.
weight_decay: 0.00001

# logging arguments
val_iter: 20000

